### ISSUE TITLE
thanks g 

### ISSUE THREAD

**Issue by dschaf** [Micca1338/FortniteSDK#3]
thanks g made me  a shitty internal using this not even the full kit tho its missing most of the useful ones.

**Comment by Nom-Youtube** [comment]
like basic helper lmao

**Comment by dschaf** [comment]
> like basic helper lmao

i know exactly what it is lmao i only come to get hub to see all these fake retards with sigs and "leaking" sdks that have been post on UC and this can be used to make a cheat carrys all data . hints the name software development kit.

**Comment by dschaf** [comment]
> like basic helper lmao

https://github.com/UnrealLord/shity-fortnite-internal-source heres a example retard. "basic helper" lmao dont embarrass yourself it is basic u got one thing correct ; ) sense its not even the full sdk
